<?php

/**
 * @file
 * Contains custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom module.
    case 'help.page.custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module to create Product content type and block to render QR code for product purchase link') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_theme() {
  return [
    'product_qr_code_block' => [
      'variables' => [
        'image' => [],
      ],
    ],
  ];
}
